### ISSUE TITLE
Schematic Submissions

### ISSUE THREAD

**Issue by timChase98** [sdowty/ECE388#2]
- [x] All files for your project should be in the version control
- [x] Missing Schematic 
- [x] USB connector not on edge of board and incorrect footprint
- [x] Volt Meters do not use BNC connectors   

Please address these issues and push your changes.  Then create a new release, increment the tag and close this issue.  I will review the changes and mark this as complete or reopen the issue with additional feedback.

**Comment by sdowty** [comment]
I closed this issue so that you would take a look at my schematic, I have not yet moved the USB connector.

**Comment by timChase98** [comment]
- [x] USB shield pins should be connected to gnd 
- [x] Add a pull up resistor to the reset line of the uController
- [x] How do you intend to attach probes to your circuit?

**Comment by sdowty** [comment]
I will be putting a large via in the PCB so that I can screw a female banana jack into it.

**Comment by timChase98** [comment]
Use a plated through hole not a via

**Comment by sdowty** [comment]
Ok, other than that is the schematic okay to make the PCB?

**Comment by timChase98** [comment]
I'll accept it.  You should move on to layout
