### ISSUE TITLE
Board Submission

### ISSUE THREAD

**Issue by timChase98** [sdowty/ECE388#3]
- [x] Review the submission guidelines [HERE](https://github.com/timChase98/388Example)
- [x] All project files should be version controlled
- [x] Boards will not be graded unless both Eagle files and correctly generated Gerber files are present
- [x] All traces should hit the center of pads
- [x] Power traces should have a minimum width of 12 mil or run through a plane
- [x] Silkscreen labels must include
  - [x] Your Name
  - [x] Project Name
  - [x] Date
  - [x] Version/Rev
  - [x] Github Link
- [x] Check stock sheet for correct footprints for 
  - [x] USB connector
  - [x] OLED display
  - [x] Switch
- [x] Your project would fit on a much smaller board
- [x] Placement of fiducials should be 
  - [x] FID1 lower left 
  - [x] FID2 upper left
  - [x] FID3 lower right

These are initial comments meant to guide you though the layout process.  I will not look at your board again until your schematic passes review.  This is to reduce the workload on you by limiting the number of times you need to relayout your board due to schematic errors.  

Please address these issues and push your changes. Then create a new release, increment the tag and close this issue. I will review the changes and mark this as complete or reopen the issue with additional feedback.

**Comment by sdowty** [comment]
I think that I made all of these changes. But, there is probably something else wrong with it.

**Comment by timChase98** [comment]
- [x] Wrong cam processor
- [x] Your USB connector is backwards 
- [x] Don't add the LCD just add a connector for it.  
- [x] Use the normalize text ULP to set the text width to .15mm
